"""Test ``X_or_default`` methods."""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


# pylint: disable=missing-docstring


import pathlib
import unittest


import aas_core3_1.types as aas_types


import tests.common_xmlization


class TestExtension(unittest.TestCase):
    def test_value_type_or_default_against_recorded(self) -> None:
        for minimal_or_maximal in ["minimal", "maximal"]:
            instance = tests.common_xmlization.must_load(
                pathlib.Path(
                    tests.common.TEST_DATA_DIR
                    / "Xml"
                    / "Expected"
                    / "extension"
                    / f"{minimal_or_maximal}.xml"
                )
            )

            assert isinstance(instance, aas_types.Extension)

            log = [tests.common.trace(instance.value_type_or_default())]

            got_text = tests.common.trace_log_as_text_file_content(log)

            expected_path = pathlib.Path(
                tests.common.TEST_DATA_DIR
                / "test_X_or_default"
                / "extension"
                / f"on_{minimal_or_maximal}.xml"
                / "value_type_or_default.trace"
            )

            tests.common.record_or_check(expected_path, got_text)


class TestQualifier(unittest.TestCase):
    def test_kind_or_default_against_recorded(self) -> None:
        for minimal_or_maximal in ["minimal", "maximal"]:
            instance = tests.common_xmlization.must_load(
                pathlib.Path(
                    tests.common.TEST_DATA_DIR
                    / "Xml"
                    / "Expected"
                    / "qualifier"
                    / f"{minimal_or_maximal}.xml"
                )
            )

            assert isinstance(instance, aas_types.Qualifier)

            log = [tests.common.trace(instance.kind_or_default())]

            got_text = tests.common.trace_log_as_text_file_content(log)

            expected_path = pathlib.Path(
                tests.common.TEST_DATA_DIR
                / "test_X_or_default"
                / "qualifier"
                / f"on_{minimal_or_maximal}.xml"
                / "kind_or_default.trace"
            )

            tests.common.record_or_check(expected_path, got_text)


class TestSubmodel(unittest.TestCase):
    def test_kind_or_default_against_recorded(self) -> None:
        for minimal_or_maximal in ["minimal", "maximal"]:
            instance = tests.common_xmlization.must_load(
                pathlib.Path(
                    tests.common.TEST_DATA_DIR
                    / "Xml"
                    / "Expected"
                    / "submodel"
                    / f"{minimal_or_maximal}.xml"
                )
            )

            assert isinstance(instance, aas_types.Submodel)

            log = [tests.common.trace(instance.kind_or_default())]

            got_text = tests.common.trace_log_as_text_file_content(log)

            expected_path = pathlib.Path(
                tests.common.TEST_DATA_DIR
                / "test_X_or_default"
                / "submodel"
                / f"on_{minimal_or_maximal}.xml"
                / "kind_or_default.trace"
            )

            tests.common.record_or_check(expected_path, got_text)


class TestSubmodelElementList(unittest.TestCase):
    def test_order_relevant_or_default_against_recorded(self) -> None:
        for minimal_or_maximal in ["minimal", "maximal"]:
            instance = tests.common_xmlization.must_load(
                pathlib.Path(
                    tests.common.TEST_DATA_DIR
                    / "Xml"
                    / "Expected"
                    / "submodelElementList"
                    / f"{minimal_or_maximal}.xml"
                )
            )

            assert isinstance(instance, aas_types.SubmodelElementList)

            log = [tests.common.trace(instance.order_relevant_or_default())]

            got_text = tests.common.trace_log_as_text_file_content(log)

            expected_path = pathlib.Path(
                tests.common.TEST_DATA_DIR
                / "test_X_or_default"
                / "submodelElementList"
                / f"on_{minimal_or_maximal}.xml"
                / "order_relevant_or_default.trace"
            )

            tests.common.record_or_check(expected_path, got_text)


if __name__ == "__main__":
    unittest.main()


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
